# Import Pandas

In [4]:
import pandas as pd

# Import data

In [11]:
names=['Id','Title','Year','Rating','Voting','Duration','Gonre']
data=pd.read_csv('imdb_top_10000.txt',sep='\t',index_col=0,names=names)

# Explore data

### data.head() gives us first five elements

In [ ]:
data.head()

### data.head(n) gives first n elements

In [14]:
data.head(8)

,Title,Year,Rating,Voting,Duration,Gonre
Id,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
tt0109830,Forrest Gump (1994),1994,8.7,368994,142 mins.,Comedy|Drama|Romance
tt0169547,American Beauty (1999),1999,8.6,338332,122 mins.,Drama
tt0499549,Avatar (2009),2009,8.1,336855,162 mins.,Action|Adventure|Fantasy|Sci-Fi

In [15]:
data.head(10005)

,Title,Year,Rating,Voting,Duration,Gonre
Id,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller
...,...,...,...,...,...,...
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

### data.tail() gives five elements from last

In [16]:
data.tail()

,Title,Year,Rating,Voting,Duration,Gonre
Id,,,,,,
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [17]:
data.tail(8)

,Title,Year,Rating,Voting,Duration,Gonre
Id,,,,,,
tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, tt0111161 to tt0279977
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     10000 non-null  object
 1   Year      10000 non-null  int64
 2   Rating    10000 non-null  float64
 3   Voting    10000 non-null  int64
 4   Duration  10000 non-null  object
 5   Gonre     9999 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 546.9+ KB

### data describe only works on int and float

In [20]:
data.describe()

               Year        Rating         Voting
count  10000.000000  10000.000000   10000.000000
mean    1993.472800      6.386070   16604.012800
std       14.829924      1.189933   34563.459698
min     1950.000000      1.500000    1356.000000
25%     1986.000000      5.700000    2333.750000
50%     1998.000000      6.600000    4980.500000
75%     2005.000000      7.200000   15277.750000
max     2011.000000      9.200000  619479.000000

In [5]:
top_kannada_movies=pd.read_csv('Top kannada movies.csv',index_col=0)

In [24]:
top_kannada_movies.head(10)

,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
Position,,,,,,,,,,,,,,
1,tt3394420,2018-12-29,2018-12-29,NaN,Ulidavaru Kandanthe,https://www.imdb.com/title/tt3394420/,movie,8.4,154.0,2014,"Crime, Drama, Thriller",6849,2014-03-28,Rakshit Shetty
2,tt7838252,2018-12-29,2018-12-29,NaN,K.G.F: Chapter 1,https://www.imdb.com/title/tt7838252/,movie,8.2,156.0,2018,"Action, Drama",38023,2018-12-20,Prashanth Neel
3,tt2358592,2018-12-29,2018-12-29,NaN,Lucia,https://www.imdb.com/title/tt2358592/,movie,8.3,135.0,2013,"Drama, Sci-Fi, Thriller",11552,2013-07-20,Pawan Kumar
4,tt4432480,2018-12-29,2018-12-29,NaN,RangiTaranga,https://www.imdb.com/title/tt4432480/,movie,8.3,149.0,2015,"Mystery, Thriller",12541,2015-07-03,Anup Bhandari
5,tt4881362,2018-12-30,2018-12-30,NaN,Thithi,https://www.imdb.com/title/tt4881362/,movie,8.2,123.0,2015,Drama,2498,2015-08-10,Raam Reddy
6,tt8602654,2018-12-29,2018-12-29,NaN,"Sarkari. Hi. Pra. Shale Kasaragodu, Koduge: Ra...",https://www.imdb.com/title/tt8602654/,movie,8.6,147.0,2018,Drama,1294,2018-08-23,Rishab Shetty
7,tt3320542,2018-12-29,2018-12-29,NaN,Ugramm,https://www.imdb.com/title/tt3320542/,movie,8.1,132.0,2014,"Action, Crime, Drama",5218,2014-02-21,Prashanth Neel
8,tt4909506,2018-12-29,2018-12-29,NaN,Godhi Banna Sadharana Mykattu,https://www.imdb.com/title/tt4909506/,movie,8.7,144.0,2016,"Drama, Thriller",2617,2016-06-03,Hemanth M. Rao
9,tt2330098,2018-12-29,2018-12-29,NaN,Upendra,https://www.imdb.com/title/tt2330098/,movie,8.8,138.0,1999,"Drama, Thriller",2476,1999-12-31,Upendra
10,tt0986329,2018-12-29,2018-12-29,NaN,Mungaru Male,https://www.imdb.com/title/tt0986329/,movie,8.3,143.0,2006,"Comedy, Music, Romance",2886,2006-12-29,Yograj Bhat

# sort data

In [12]:
top_kannada_movies.sort_values(by='IMDb Rating',ascending=False)

,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
Position,,,,,,,,,,,,,,
9,tt2330098,2018-12-29,2018-12-29,NaN,Upendra,https://www.imdb.com/title/tt2330098/,movie,8.8,138.0,1999,"Drama, Thriller",2476,1999-12-31,Upendra
21,tt0250745,2018-12-29,2018-12-29,NaN,Sri Krishna Deva Raya,https://www.imdb.com/title/tt0250745/,movie,8.8,216.0,1970,"Drama, History",70,1970-01-01,B. Ramakrishnaiah Panthulu
8,tt4909506,2018-12-29,2018-12-29,NaN,Godhi Banna Sadharana Mykattu,https://www.imdb.com/title/tt4909506/,movie,8.7,144.0,2016,"Drama, Thriller",2617,2016-06-03,Hemanth M. Rao
6,tt8602654,2018-12-29,2018-12-29,NaN,"Sarkari. Hi. Pra. Shale Kasaragodu, Koduge: Ra...",https://www.imdb.com/title/tt8602654/,movie,8.6,147.0,2018,Drama,1294,2018-08-23,Rishab Shetty
18,tt6805436,2018-12-29,2018-12-29,NaN,Navagraha,https://www.imdb.com/title/tt6805436/,movie,8.5,147.0,2008,"Action, Crime, Thriller",97,2008-11-06,Dinakar Thoogudeepa
1,tt3394420,2018-12-29,2018-12-29,NaN,Ulidavaru Kandanthe,https://www.imdb.com/title/tt3394420/,movie,8.4,154.0,2014,"Crime, Drama, Thriller",6849,2014-03-28,Rakshit Shetty
3,tt2358592,2018-12-29,2018-12-29,NaN,Lucia,https://www.imdb.com/title/tt2358592/,movie,8.3,135.0,2013,"Drama, Sci-Fi, Thriller",11552,2013-07-20,Pawan Kumar
4,tt4432480,2018-12-29,2018-12-29,NaN,RangiTaranga,https://www.imdb.com/title/tt4432480/,movie,8.3,149.0,2015,"Mystery, Thriller",12541,2015-07-03,Anup Bhandari
10,tt0986329,2018-12-29,2018-12-29,NaN,Mungaru Male,https://www.imdb.com/title/tt0986329/,movie,8.3,143.0,2006,"Comedy, Music, Romance",2886,2006-12-29,Yograj Bhat
11,tt6054758,2018-12-29,2018-12-29,NaN,Kirik Party,https://www.imdb.com/title/tt6054758/,movie,8.3,159.0,2016,"Comedy, Drama",4532,2016-12-30,Rishab Shetty
19,tt0233270,2018-12-29,2018-12-29,NaN,Babruvahana,https://www.imdb.com/title/tt0233270/,movie,8.3,160.0,1977,"Action, Drama, History",320,1977-02-16,Hunsur Krishnamurthy
16,tt5471570,2018-12-29,2018-12-29,NaN,Amrutha Varshini,https://www.imdb.com/title/tt5471570/,movie,8.2,147.0,1997,"Drama, Romance",180,1997-01-29,Dinesh Babu
25,tt7479902,2018-12-29,2018-12-29,NaN,Gultoo,https://www.imdb.com/title/tt7479902/,movie,8.2,128.0,2018,"Crime, Drama",909,2018-03-30,Janardhan Chikkanna
22,tt0309764,2018-12-29,2018-12-29,NaN,Kavirathna Kaalidaasa,https://www.imdb.com/title/tt0309764/,movie,8.2,189.0,1983,"Drama, History, Musical, Romance",237,1983-02-05,Renuka Sharma
2,tt7838252,2018-12-29,2018-12-29,NaN,K.G.F: Chapter 1,https://www.imdb.com/title/tt7838252/,movie,8.2,156.0,2018,"Action, Drama",38023,2018-12-20,Prashanth Neel
17,tt6169798,2018-12-30,2018-12-30,NaN,Rama Rama Re,https://www.imdb.com/title/tt6169798/,movie,8.2,112.0,2016,"Drama, Thriller",620,2016-10-21,"Satyaprakash, D. Satya Prakash"
5,tt4881362,2018-12-30,2018-12-30,NaN,Thithi,https://www.imdb.com/title/tt4881362/,movie,8.2,123.0,2015,Drama,2498,2015-08-10,Raam Reddy
7,tt3320542,2018-12-29,2018-12-29,NaN,Ugramm,https://www.imdb.com/title/tt3320542/,movie,8.1,132.0,2014,"Action, Crime, Drama",5218,2014-02-21,Prashanth Neel
23,tt3006576,2018-12-29,2018-12-29,NaN,Simple Agi Ondh Love Story,https://www.imdb.com/title/tt3006576/,movie,8.0,130.0,2013,"Comedy, Romance",1990,2013-03-08,Suni
26,tt1402530,2018-12-29,2018-12-29,NaN,Na Ninna Bidalare,https://www.imdb.com/title/tt1402530/,movie,8.0,NaN,1979,NaN,61,NaN,Vijay
32,tt0290632,2018-12-29,2018-12-29,NaN,Goa Dalli CID 999,https://www.imdb.com/title/tt0290632/,movie,8.0,145.0,1968,"Crime, Thriller",69,NaN,Dhorairaj Bhagavan
15,tt7938336,2018-12-29,2018-12-29,NaN,Tagaru,https://www.imdb.com/title/tt7938336/,movie,7.9,129.0,2018,"Action, Crime",1212,2018-02-23,Soori
29,tt1773441,2018-12-29,2018-12-29,NaN,Gaalipata,https://www.imdb.com/title/tt1773441/,movie,7.9,146.0,2008,"Comedy, Musical, Romance",671,2008-01-18,Yograj Bhat
24,tt0871012,2018-12-29,2018-12-29,NaN,Rama Shama Bhama,https://www.imdb.com/title/tt0871012/,movie,7.8,180.0,2005,Comedy,457,2005-12-09,Ramesh Aravind
13,tt0247203,2018-12-29,2018-12-29,NaN,Bhakta Prahlada,https://www.imdb.com/title/tt0247203/,movie,7.6,151.0,1967,"Drama, Musical",158,1967-01-12,Chitrapu Narayana Rao
31,tt0233329,2018-12-29,2018-12-29,NaN,Bhakta Kumbhara,https://www.imdb.com/title/tt0233329/,movie,7.6,149.0,1974,Drama,116,1974-08-24,Hunsur Krishnamurthy
14,tt5377564,2018-12-29,2018-12-29,NaN,U Turn,https://www.imdb.com/title/tt5377564/,movie,7.5,120.0,2016,"Crime, Horror, Mystery, Thriller",2934,2016-04-08,Pawan Kumar
20,tt1354036,2018-12-29,2018-12-29,NaN,Mugana Sedu,https://www.imdb.com/title/tt1354036/,movie,7.5,135.0,1980,NaN,23,NaN,Subba Rao B.A.
28,tt3075360,2018-12-29,2018-12-29,NaN,Googly,https://www.imdb.com/title/tt3075360/,movie,7.4,136.0,2013,"Comedy, Romance",2248,2013-07-19,Pawan Wadeyar
12,tt4944434,2018-12-29,2018-12-29,NaN,Jogi the King,https://www.imdb.com/title/tt4944434/,movie,7.3,172.0,2005,"Action, Drama",243,2005-08-19,Prem
27,tt7997932,2018-12-29,2018-12-29,NaN,Katheyondu Shuruvagide,https://www.imdb.com/title/tt7997932/,movie,7.3,133.0,2018,"Comedy, Romance",440,2018-07-27,Senna Hegde
30,tt2359746,2018-12-29,2018-12-29,NaN,Pancharangi,https://www.imdb.com/title/tt2359746/,movie,7.3,123.0,2010,Drama,541,2010-09-03,Yograj Bhat

In [16]:
top_kannada_movies.to_csv('kannada_movies_list',sep=' ',header=True)